wheel_build_task:
  name: Build Rasterio wheels for Mac ARM64.
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode
  env:
    BUILD_PREFIX: /private/tmp/local
    REPO_DIR: Fiona
    BUILD_COMMIT: rel-1.10b3
    CIRRUS_CLONE_SUBMODULES: true
    PATH: /opt/homebrew/opt/python@3.10/bin:$PATH
    PLAT: "arm64"
    BUILD_DEPENDS: "setuptools cython~=3.0.2 wheel"
    TEST_DEPENDS: "attrs pytest click mock boto3 packaging hypothesis wheel pytz fsspec aiohttp requests pyparsing shapely"
    MACOSX_DEPLOYMENT_TARGET: "11.0"

  install_pre_requirements_script:
    - brew install pkg-config python@3.10
    - ln -s /opt/homebrew/opt/python@3.10/bin/python3.10 /opt/homebrew/opt/python@3.10/bin/python
  brew_remove_pkgs_script:
    - brew remove -f --ignore-dependencies liblerc webp zstd libtiff libxcb libxdcmp curl php lcms2 xmlto ghostscript lz4 openjpeg xz gettext giflib rtmpdump brotli
  build_wheel_script:
    - mkdir -p $BUILD_PREFIX/include
    - mkdir -p $BUILD_PREFIX/lib/pkgconfig
    - mkdir -p $BUILD_PREFIX/bin
    - mkdir -p $BUILD_PREFIX/share/doc
    - mkdir -p $BUILD_PREFIX/share/man/man{1,3,5,7}
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - clean_code $REPO_DIR $BUILD_COMMIT
    - pre_build
    - MACOSX_DEPLOYMENT_TARGET=11.0
    - GDAL_CONFIG=$BUILD_PREFIX/bin/gdal-config
    - PROJ_DATA=$BUILD_PREFIX/share/proj
    - CIBW_PRERELEASE_PYTHONS=True
    - CIBW_ARCH=$PLAT
    - python3 -m pip install --upgrade pip
    - python3 -m pip install cibuildwheel==2.20.0
    - python3 -m cibuildwheel --output-dir wheelhouse
  wheels_artifacts:
    path: "wheelhouse/*.whl"
