---
name: Wheels

on: [push, pull_request]

env:
  REPO_DIR: Fiona
  WHEEL_SDIR: wheelhouse
  SETUPTOOLS_USE_DISTUTILS: stdlib

jobs:
  build:
    name: ${{ matrix.python }} ${{ matrix.os-name }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ARM64" ]
        python: [ "3.9" ]
        platform: [ "arm64"]
        macos-target: [ "11" ]
        os-name: ["osx"]
        exclude:
          - os: "macos-latest"
            platform: "i686"
    env:
      BUILD_COMMIT: 1.8.21
      PLAT: "${{ matrix.platform }}"
      MB_PYTHON_VERSION: "${{ matrix.python }}"
      MB_ML_VER: "2014"
      BUILD_DEPENDS: "oldest-supported-numpy cython==0.29.26 wheel==0.34.2"
      TEST_DEPENDS: "oldest-supported-numpy attrs==21.4.0 pytest==6.2.5 click==8.0.3 mock boto3 packaging hypothesis==4.38.1 wheel==0.34.2 pytz"
      TRAVIS_OS_NAME: ${{ matrix.os-name }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos-target }}
      PIP_CMD: pip3
      PYTHON_EXE: python3
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Python
        run: |
          brew install python@${MB_PYTHON_VERSION}
          PATH=/opt/homebrew/opt/python@${MB_PYTHON_VERSION}/libexec/bin:$PATH
          python -c "import sys; print(sys.version)" | awk -F \. {'print $1$2'}
      - name: Build Wheel
        run: bash -x .github/workflows/build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: wheelhouse/*.whl
